### ISSUE TITLE
Unable to instantiate activity ComponentInfo{com.example.jhordan.people_mvvm/com.example.jhordan.people_mvvm.view.PeopleActivity}: java.lang.ClassNotFoundException: Didn't find class "com.example.jhordan.people_mvvm.view.PeopleActivity" on path: /data/app/com.example.jhordan.people_mvvm-1.apk

### ISSUE THREAD

**Issue by hamedgol** [erikcaffrey/People-MVVM#24]
Hi 
I found this error when lunching app 

` java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.example.jhordan.people_mvvm/com.example.jhordan.people_mvvm.view.PeopleActivity}: java.lang.ClassNotFoundException: Didn't find class "com.example.jhordan.people_mvvm.view.PeopleActivity" on path: /data/app/com.example.jhordan.people_mvvm-1.apk
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2106)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
                                                                                   at android.app.ActivityThread.access$600(ActivityThread.java:141)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                   at android.os.Looper.loop(Looper.java:137)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5041)
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                                                   at dalvik.system.NativeStart.main(Native Method)
                                                                                Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.jhordan.people_mvvm.view.PeopleActivity" on path: /data/app/com.example.jhordan.people_mvvm-1.apk
                                                                                   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:65)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
                                                                                   at android.app.Instrumentation.newActivity(Instrumentation.java:1054)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2097)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
                                                                                   at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                   at android.os.Looper.loop(Looper.java:137) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5041) 
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                                                                                   at dalvik.system.NativeStart.main(Native Method) `

**Comment by ahmad73jam** [comment]
1- edit file PeopleApplication.java change it to extend MultiDexApplication
public class MyApplication extends MultiDexApplication 

2- add the multidex support library to your project:

dependencies {
  compile 'com.android.support:multidex:1.0.1'
}

**Comment by erikcaffrey** [comment]
Fixed -> https://github.com/erikcaffrey/People-MVVM/pull/28

The project is already working 😉
